# Generated by Django 3.2.8 on 2022-08-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20220806_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFils',
            new_name='UserFilms',
        ),
    ]
