# Generated by Django 3.2.8 on 2022-08-06 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_userfils_userfilms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='users',
        ),
        migrations.AddField(
            model_name='film',
            name='users',
            field = models.ManyToManyField(related_name='films', through='films.UserFilms', to=settings.AUTH_USER_MODEL),
        )

    ]
